" ----------------------------------------------------------------
" THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             -
" NEVER CHANGE IT MANUALLY, PLEASE!                           -
" ----------------------------------------------------------------
INCLUDE lz_grouptestu01.
"Z_MODULETEST